---
name: Checks

# Which event will trigger the jobs (here when code is pushed to github)
on: [push] 

jobs:
  # id for the job
  test-lint:
    # How this job will be seen on git hub (user friendly name)
    name: Test and Lint
    # which runner on github we want to run this job
    runs-on: ubuntu-20.04
    # steps for this job
    steps:
        # user friendly name for the step 
      - name: Login to Docker hub
        # use this github provided action to log in to docker hub
        uses: docker/login-action@v1
        with: 
          # use these credentials that I provided to you on github
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      # for the following steps we need the code. Thus check it out
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test" 
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"